sudo: false
language: python
matrix:
  allow_failures:
  - env: TOXENV=py37-djangodev-sqlite
  - env: TOXENV=py37-djangodev-mysql
  - env: TOXENV=py37-djangodev-postgresql
  include:
  - python: 3.7
    env: TOXENV=py37-django22-sqlite
  - python: 3.7
    env: TOXENV=py37-django30-sqlite
  - python: 3.7
    env: TOXENV=py37-django31-sqlite
  - python: 3.8
    env: TOXENV=py38-django31-sqlite
  - python: 3.7
    env: TOXENV=py37-djangodev-sqlite
  - python: 3.7
    env: TOXENV=py37-djangodev-mysql
  - python: 3.7
    env: TOXENV=py37-djangodev-postgresql
  - python: 3.7
    env: TOXENV=checkqa
  - python: 3.7
    env: TOXENV=docs
  - stage: deploy
    python: 3.7
    script: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-cities-light/upload
      distributions: sdist bdist_wheel
      password:
        secure: TCH5tGIggL2wsWce2svMwpEpPiwVOYqq1R3uSBTexszleP0OafNq/wZk2KZEReR5w1Aq68qp5F5Eeh2ZjJTq4f9M4LtTvqQzrmyNP55DYk/uB1rBJm9b4gBgMtAknxdI2g7unkhQEDo4suuPCVofM7rrDughySNpmvlUQYDttHQ=
      skip_existing: true
      on:
        tags: true
        repo: jazzband/django-cities-light
        python: 3.7
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
