language: python
services:
  - mysql
  - postgresql
cache:
  pip: true
python:
  - 3.6
  - 3.7
  - 3.8
jobs:
  allow_failures:
  - env: TOXENV=py37-djangodev-sqlite
  - env: TOXENV=py37-djangodev-mysql
  - env: TOXENV=py37-djangodev-postgresql
  include:
  - stage: deploy
    if: tag IS present
    python: 3.7
    script: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-cities-light/upload
      distributions: sdist bdist_wheel
      password:
        secure: POps88GX3PHO2xb+XaX/5IlnpQGWwWI+vw/BFPoiJABOqwcOms3vpFT7XKYxYG40e7WSIifndzn8rS2hYr2C4tlZvyCf1+BMfLtNMzGLQAOJAPn+qO4BwEdBdwUBdkGmpHVaO9wndjLHKuimQ8HM4qmdKJU74zp39Kpulo3hBQM=
      skip_existing: true
      on:
        tags: true
        repo: jazzband/django-cities-light
install:
- travis_retry pip install -U pip
- travis_retry pip install tox-travis codecov
script:
- tox -v
after_success:
- codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
