# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_auto_20171229_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='SubRegion',
        ),
        migrations.AlterModelOptions(
            name='subregion',
            options={'ordering': ['name'], 'verbose_name': 'SubRegion', 'verbose_name_plural': 'SubRegions'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='department',
            new_name='SubRegion',
        ),
    ]
