# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20171229_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='SubRegion',
        ),
        migrations.AddField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.SubRegion'),
        ),
    ]
