# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20171229_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together=set([]),
        ),
    ]
