# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_auto_20171229_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together=set([('country', 'name'), ('country', 'slug')]),
        ),
    ]
