# Generated by Django 5.0.6 on 2024-06-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                to_field="geoname_id",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
                to_field="geoname_id",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.subregion",
                to_field="geoname_id",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                to_field="geoname_id",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                to_field="geoname_id",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
                to_field="geoname_id",
            ),
        ),
    ]
