# Generated by Django 6.0.2 on 2026-02-16 16:32

import autoslug.fields
import cities_light.abstract_models
import cities_light.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="alternate_names",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="alternate names"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="display_name",
            field=models.CharField(max_length=200, verbose_name="display name"),
        ),
        migrations.AlterField(
            model_name="city",
            name="feature_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="geoname_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Geonames ID"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_ascii",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="ASCII name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="population",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="population"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="search_names",
            field=cities_light.abstract_models.ToSearchTextField(
                blank=True,
                db_index=True,
                default="",
                max_length=4000,
                verbose_name="search names",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name_ascii", verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.subregion",
                verbose_name="subregion",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="timezone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                null=True,
                validators=[cities_light.validators.timezone_validator],
                verbose_name="timezone",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="translations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="translations"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="alternate_names",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="alternate names"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code2",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                unique=True,
                verbose_name="ISO 3166-1 alpha-2",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code3",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                unique=True,
                verbose_name="ISO 3166-1 alpha-3",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(
                choices=[
                    ("OC", "Oceania"),
                    ("EU", "Europe"),
                    ("AF", "Africa"),
                    ("NA", "North America"),
                    ("AN", "Antarctica"),
                    ("SA", "South America"),
                    ("AS", "Asia"),
                ],
                db_index=True,
                max_length=2,
                verbose_name="continent",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="geoname_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Geonames ID"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name_ascii",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="ASCII name"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone code"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name_ascii", verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="tld",
            field=models.CharField(
                blank=True, db_index=True, max_length=5, verbose_name="top-level domain"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="translations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="translations"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="alternate_names",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="alternate names"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="display_name",
            field=models.CharField(max_length=200, verbose_name="display name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="geoname_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Geonames code",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="geoname_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Geonames ID"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_ascii",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="ASCII name"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name_ascii", verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="translations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="translations"
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="alternate_names",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="alternate names"
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="display_name",
            field=models.CharField(max_length=200, verbose_name="display name"),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="geoname_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Geonames code",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="geoname_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Geonames ID"
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="name_ascii",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="ASCII name"
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name_ascii", verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="translations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="translations"
            ),
        ),
    ]
