# Generated by Django 6.0.2 on 2026-02-17 04:11

import cities_light.abstract_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='search_names',
            field=cities_light.abstract_models.ToSearchTextField(blank=True, default='', max_length=4000, verbose_name='search names'),
        ),
    ]
